[target.aarch64-unknown-linux-gnu]
linker = "aarch64-ostl-linux-gcc  -mcpu=cortex-a35+crc -mbranch-protection=standard --sysroot=/home/ucanboz/Desktop/repositories/STM32/STM32MPU-Ecosystem-v6.0.0/Distribution-Package/build-openstlinuxweston-stm32mp25-disco/tmp-glibc/work/cortexa35-ostl-linux/tcpserver/1.0+git/recipe-sysroot"
ar = "aarch64-ostl-linux-gcc-ar"
